builds:
  - binary: "net-cli"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: net-cli
    homepage: https://github.com/kirre02/net-cli
    commit_author:
      name: kirre02
    repository:
      owner: kirre02
      name: homebrew-tap
      branch: main
checksum:
  name_template: "checksums.txt"
